export const Form_Project = "Form_Project"
export const Get_Data = "Get_Data"
export const Add_NewProject = "Add_NewProject"
export const Actual_Project = "Actual_Project"
export const Delete_Project = "Delete_Project"
export const Get_DataProject = "Get_DataProject"
export const Add_Task = "Add_Task"
export const Delete_Task = "Delete_Task"
export const Select_Task = "Select_Task"
export const Atualizar_Task = "Atualizar_Task"
export const Message_Error = "Message_Error"
//alert
export const Show_Alert = "Show_Alert"
export const Hide_Alert = "Hide_Alert"
//Auth
export const Successful_Registration = "Successful_Registration"
export const Register_Error = "Register_Error"
export const Get_User = "Get_User"
export const Login_Successful = "Login_Successful"
export const Login_Error = "Login_Error"
export const Close_Section = "Close_Section"